import type { Metadata } from "next";
import { Geist, Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SignIn from "./components/SignIn";
import SignOut from "./components/SignOut";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ['800', '700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <nav>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <SignIn />
          <SignOut />
        </nav>
        {children}
      </body>
    </html>
  );
}